/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
 */

function fibo(max: number): number {
  function inner(
    [_1, _2]: number[],
    fibs: number[],
    total: number
  ): [number[], number] {
    const _3 = _1 + _2;
    const isPair = _3 % 2 === 0;
    return max < _3
      ? [fibs, total]
      : inner([_2, _3], [...fibs, _3], isPair ? total + _3 : total);
  }

  const [fibs, total] = inner([1, 2], [2], 2);
  return total;
}

assert.deepStrictEqual(fibo(4000000), 4613732);
